# Generated by Django 4.2.30 on 2026-10-07 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_add_password_reset_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(db_index=True, max_length=15)),
                ("code_hash", models.CharField(max_length=128)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("login", "Login"), ("reset", "Reset")],
                        default="login",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "auth_otp_code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["phone_number", "is_used"],
                name="auth_otp_co_phone_n_4a2511_idx",
            ),
        ),
    ]
