# Generated by Django 4.2.30 on 2026-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("order_status_change", "Order Status Change"),
                    ("shipping_update", "Shipping Update"),
                    ("password_reset", "Password Reset"),
                    ("welcome", "Welcome"),
                    ("wishlist_discount", "Wishlist Product Discount"),
                    ("generic", "Generic"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("order_status_change", "Order Status Change"),
                    ("shipping_update", "Shipping Update"),
                    ("password_reset", "Password Reset"),
                    ("welcome", "Welcome"),
                    ("wishlist_discount", "Wishlist Product Discount"),
                    ("generic", "Generic"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
