# Generated by Django 4.2.30 on 2026-10-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotificationpreference",
            name="email_account",
        ),
        migrations.RemoveField(
            model_name="usernotificationpreference",
            name="email_order_updates",
        ),
        migrations.RemoveField(
            model_name="usernotificationpreference",
            name="email_promotions",
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="sms_account",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="sms_order_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="sms_promotions",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("order_status_change", "Order Status Change"),
                    ("shipping_update", "Shipping Update"),
                    ("welcome", "Welcome"),
                    ("wishlist_discount", "Wishlist Product Discount"),
                    ("generic", "Generic"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("order_status_change", "Order Status Change"),
                    ("shipping_update", "Shipping Update"),
                    ("welcome", "Welcome"),
                    ("wishlist_discount", "Wishlist Product Discount"),
                    ("generic", "Generic"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
