# Generated by Django 4.2.30 on 2026-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0003_remove_usernotificationpreference_email_account_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("order_status_change", "Order Status Change"),
                    ("shipping_update", "Shipping Update"),
                    ("welcome", "Welcome"),
                    ("wishlist_discount", "Wishlist Product Discount"),
                    ("generic", "Generic"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type",),
                name="uq_template_type_active",
            ),
        ),
    ]
