# Generated by Django 4.2.30 on 2026-08-13 22:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("object_id", models.UUIDField()),
                ("file", models.FileField(upload_to="media_libm/%Y/%m/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("thumbnail", "Thumbnail"),
                            ("360", "360 View"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=500)),
                ("caption", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": ["productoption", "collection", "page"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "media_libm",
                "ordering": ["position"],
            },
        ),
    ]
