# Generated by Django 4.2.30 on 2026-09-15 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="زمان پایان مهلت تخفیف (اختیاری)", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="درصد تخفیف بین ۱ تا ۹۹",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="درصد تخفیف باید حداقل ۱ درصد باشد."
                    ),
                    django.core.validators.MaxValueValidator(
                        99, message="درصد تخفیف نمی\u200cتواند بیشتر از ۹۹ درصد باشد."
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="مبلغ پس از تخفیف به تومان (محاسبه خودکار)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
