# Generated by Django 4.2.30 on 2026-09-15 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_expires_at_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('image', models.FileField(blank=True, max_length=500, null=True, upload_to='products/%Y/%m/')),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_image',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
