# Generated by Django 4.2.30 on 2026-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Product weight in grams (used for post shipping calculations)",
            ),
        ),
    ]
