# Generated by Django 4.2.30 on 2026-09-22 03:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordering index (0 = first item shown)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_product",
                    models.ForeignKey(
                        help_text="The product on whose page these related items appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_related_targets",
                        to="products.product",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        help_text="The recommended complementary product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_related_sources",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "products_related_product",
                "ordering": ["position", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_product", "position"],
                        name="products_re_source__3b48ed_idx",
                    )
                ],
                "unique_together": {("source_product", "target_product")},
            },
        ),
    ]
