# Generated by Django 4.2.30 on 2026-09-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_relatedproduct"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="relatedproduct",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="relatedproduct",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("complete_look", "Complete the Look"),
                    ("suggested", "Suggested"),
                ],
                db_index=True,
                default="complete_look",
                help_text="Complete look (manual only) vs Suggested (manual+auto fallback)",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relatedproduct",
            unique_together={("source_product", "target_product", "relation_type")},
        ),
        migrations.AddIndex(
            model_name="relatedproduct",
            index=models.Index(
                fields=["source_product", "relation_type", "position"],
                name="products_re_source__b3876e_idx",
            ),
        ),
    ]
