# Generated by Django 4.2.30 on 2026-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_collections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("slug",),
                name="uq_collection_slug_active",
            ),
        ),
    ]
