# Generated by Django 4.2.30 on 2026-08-13 22:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "hero_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="collections/banners/"
                    ),
                ),
                ("landing_page_content", models.TextField(blank=True)),
                ("seo_metadata", models.JSONField(blank=True, default=dict)),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("published_from", models.DateTimeField(blank=True, null=True)),
                ("published_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "collection",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="store_collections.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_links",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "collection_product",
                "ordering": ["position", "id"],
                "unique_together": {("collection", "product")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="store_collections.CollectionProduct",
                to="products.product",
            ),
        ),
    ]
