# Generated by Django 4.2.30 on 2026-10-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_options", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="optionvalue",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productoption",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="optionvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("option", "value"),
                name="uq_optionvalue_option_value_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="productoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("product", "name"),
                name="uq_productoption_product_name_active",
            ),
        ),
    ]
