# Generated by Django 4.2.30 on 2026-10-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_seed_discount_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="key",
            field=models.CharField(
                db_index=True,
                help_text="One of: homepage, header, footer, announcement, discount_section",
                max_length=100,
            ),
        ),
    ]
