# Generated by Django 4.2.30 on 2026-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_alter_sitecontent_key"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sitecontent",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("slug",),
                name="uq_page_slug_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("key",),
                name="uq_sitecontent_key_active",
            ),
        ),
    ]
