# Generated by Django 4.2.30 on 2026-09-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="seo_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
