# Generated by Django 4.2.30 on 2026-09-01 08:48

import common.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", common.managers.UserManager()),
            ],
        ),
    ]
