# Generated by Django 4.2.30 on 2026-09-01 12:07

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="unique_lower_email",
                violation_error_message="A user with this email already exists.",
            ),
        ),
    ]
