# Generated by Django 4.2.30 on 2026-10-07 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_user_unique_lower_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_lower_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be Iranian mobile like 09123456789.",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                models.F("phone_number"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="unique_phone_number",
                violation_error_message="A user with this phone already exists.",
            ),
        ),
    ]
