# Generated by Django 4.2.30 on 2026-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="weight",
            field=models.PositiveIntegerField(default=500, help_text="Weight in grams"),
        ),
    ]
