# Generated by Django 4.2.30 on 2026-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0002_alter_variant_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="weight",
            field=models.PositiveIntegerField(default=1, help_text="Weight in grams"),
        ),
    ]
