# Generated by Django 4.2.30 on 2026-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0003_alter_variant_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="barcode",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="sku",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("sku",),
                name="uq_variant_sku_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("barcode",),
                name="uq_variant_barcode_active",
            ),
        ),
    ]
