# Generated by Django 4.2.30 on 2026-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="wishlistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("wishlist", "product"),
                name="uq_wishlistitem_wishlist_product_active",
            ),
        ),
    ]
